export const ACTION_TYPE = {
	SET_VALUE_NOTE: 'SET_VALUE_NOTE',
	SET_VALUE_NOTES: 'SET_VALUE_NOTES',
	SET_VALUE_SEARCH_RESULT: 'SET_VALUE_SEARCH_RESULT',
	SET_VALUE_LOADING: 'SET_VALUE_LOADING',
	ERROR: 'ERROR',
	SET_USER: 'SET_USER',
	SET_VALUE_USERS: 'SET_VALUE_USERS',
	LOGOUT: 'LOGOUT',
};
